;DATE 02,23,2021
;AUTHOR KAISER,SAKHI

;PROGRAM TO SHOW THE USE OF ADC 
;ADC IS JUST LIKE ADD BUT IT ALSO ADDS THE CARRY OF PREVIOS OPERATION ,JUST LIKE AUXILARLY CARRY BUT IT CAN BE USED IN BETWEEN DB,DW,DD ETC
 

CODE SEGMENT
	ASSUME CS:CODE
	START:
	MOV AL,0FFH
	MOV AH,0FFH
	ADD AL, AH      ;ADD AND STORE THE RESULT IN AL [THIS IS THE LEAST SEGNIFICANT BYTE

	MOV BL, 0FFH    ;
	MOV BH, 0FFH
	ADC BH, BL      ;BH <- BH+BL-CARRY_OF_PREVIOVS ADDITION (THIS IS THE MOST SIGNIFICANT BYTE [BH]
	
	MOV AH, BH      ; MOV BH INTO AH , NOT AX IS THE ADDITION OF AX = AH+AL+1+BH+BL

	MOV BX, AX      ; MOV AX INTO BX , USING AX AGAIN
	MOV AX, 4C00H   ; 4C AND 00H ARGUMENTS TO 21H
	INT 21H

CODE ENDS
	END START
