;DATE 2,21,2021
;AUTHOR KAISER,SAKHI
;PROGRAM TO FIND IF NO IS EVEN OR ODD

DATA SEGMENT
	number DB 5H
	iseven DB 00H
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE, DS:DATA
	START:
		MOV AX, DATA
		MOV DS, AX
		MOV AH, number
		MOV CL, 01H
		ROR AH,CL
		JC SKIP
		MOV iseven, 01H
	SKIP:
		MOV AH, 4CH
		MOV AL, 00H
		INT 21H
CODE ENDS
END START