;DATE 24,03,2021
;AUTHOR KAISER,SAKHI

;PROGRAM TO DESMONSTRATE PARAMETER PASSING
; THERE ARE 2 METHODS TO PASS PARAMETERS TO A PROCEDURE
;1 is through register, 2 through stack

; 1 is very simple, i will be implemented the latter one :), lets roll

MSTACK SEGMENT STACK
    DW 40H DUP(0FFFFH) ; INIT STACK ;NOTE THIS IS NECCESSARY
    TOS LABEL WORD    ; THIS WILL REFER TO THE TOP OF THE STACK, 
MSTACK ENDS

DATA SEGMENT
    arr DB 04H,34H,09H,31H,65H ; THE FIRST WILL BE COUNT OF THIS ARRY IE 4H
    hgst DB 00H 
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA, SS:MSTACK
    START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, MSTACK
    MOV SS, AX
    MOV SP, OFFSET TOS

    LEA AX ,arr
    PUSH AX ; TODO: REMOVE 
    PUSH AX ; PUSH THE BASE ADDRESS OF THE ARRRAY IN TO STACK TOP    
    
    
    CALL GET_HIGHEST
    POP AX    ; SUB ROUTINE HAS PUSHED THE GREATEST HERE :) , IE TOP OF THE STACK IS THE GREATEST AT THIS POINT 
    
    MOV hgst, AL ; AS THE ARRAY IS BYTE DEFINED OUR ANSWER SHOULD BE IN AL, SAVE IT IN MEM
    
    
    MOV AX, 4C00H
    INT 21H
    
    
    
    
    ; THIS PROCEDURE WILL FIND THE HIGHEST IN AN ARRAY SUPPLIED THROUGH STACK 
GET_HIGHEST PROC NEAR 

    PUSHF
    PUSH BX
    PUSH CX

    MOV BP, SP   ; AT THIS POINT BP IS HOLDING THE BASE ADDRESS OF ARR
    MOV BX, [BP+8]
    MOV CL, BYTE PTR DS:[BX] ; MOV FIRST ELEMNT OF ARR IE COUNT INT CX

    INC BX

    ; NOW STAR
    MOV AL, BYTE PTR DS:[BX]    ;SUPPOSE AX IS THE HISHT
    BACK:
    CMP AL, BYTE PTR DS:[BX+1] 
    JG TO
    MOV AL ,BYTE PTR DS:[BX+1]
    TO:
    INC BX
    LOOP BACK


    POP CX
    POP BX
    POPF 
    
    MOV AH, 00H
          
    MOV SS:[BP+8], AX  ; PUSH AT THE SAME LOCATION WHERE I GOT THE BASE ADDRESS FROM 
    RET

ENDP GET_HIGHEST

CODE ENDS
    END START

