;DATE 24,03,2021
;AUTHOR KAISER,SAKHI

; PROGRAM TO COUNT THE NUMBER OF ONES IN A NUMBER

DATA SEGMENT
    num DW 0AAAH
    p_cout DB 00H
    msg1 DB 0DH,0AH,"Number Of One's are : $"
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
    START:
    MOV AX, DATA
    MOV DS, AX
    
    MOV AX, num
    MOV BH, 00H
    MOV BL, 0001H
    MOV CX, 10H ; MOV 16 TO CX FOR COUNT 
    BACK:
    SHR AX, 01H  ; RIGHT SHIFT BY 0NE
    JNC TO      ; IF THERE IS NO CARYY THEN MOV TO LOOP
        INC BH  ; IF THERE IS A CARRY THEN INCREMENT BH
    TO: LOOP BACK ;LOOP BACK UNTIL CX IS 0

    MOV p_cout, BH ; STORE THE RESULT IN MEM

    MOV AH, 09H
    MOV DX, OFFSET msg1
    INT 21H  
    
    MOV AH, 02H
    MOV DL, BH
    ADD DL, 30H ; ASCII ADJUSTMENT
    INT 21H

    MOV AX, 4C00H
    INT 21H 

CODE ENDS
    END START
